language: node_js
node_js: node
services: mongodb
env: MONGODB_URI=mongodb://localhost:27017/events AUTH0_CLIENT_ID=1234 AUTH0_DOMAIN=me.auth0.com AUTH0_MANAGEMENT_CLIENT_SECRET=1234 AUTH0_AUDIENCE=https://me.auth0.com/api/v2/
deploy:
  provider: heroku
